// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnD6bQe8KuAX-0ct1Yy9ABoZ2jPpvOyTU',
    appId: '1:3827096841:android:e1cd8f19dbc5caa61b87d8',
    messagingSenderId: '3827096841',
    projectId: 'my-project-68377-1709184103342',
    databaseURL: 'https://my-project-68377-1709184103342-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-68377-1709184103342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZzPKPRIywl3cvmHr3Lq_s27_kTZZucg',
    appId: '1:3827096841:ios:d8bbb709ae6b43ea1b87d8',
    messagingSenderId: '3827096841',
    projectId: 'my-project-68377-1709184103342',
    databaseURL: 'https://my-project-68377-1709184103342-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-68377-1709184103342.appspot.com',
    androidClientId: '3827096841-k0radifoh0r3c7a82vfr8sl7koftuer7.apps.googleusercontent.com',
    iosClientId: '3827096841-inhcd1op8i31198q2p2vq8806frr61gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApW-HSb9rwYf6TcfaaNKhv_9AbbLeJIus',
    appId: '1:3827096841:web:9bf14ef4fc151df01b87d8',
    messagingSenderId: '3827096841',
    projectId: 'my-project-68377-1709184103342',
    authDomain: 'my-project-68377-1709184103342.firebaseapp.com',
    databaseURL: 'https://my-project-68377-1709184103342-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-68377-1709184103342.appspot.com',
    measurementId: 'G-Z1448YX8ZM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIZzPKPRIywl3cvmHr3Lq_s27_kTZZucg',
    appId: '1:3827096841:ios:d8bbb709ae6b43ea1b87d8',
    messagingSenderId: '3827096841',
    projectId: 'my-project-68377-1709184103342',
    databaseURL: 'https://my-project-68377-1709184103342-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-68377-1709184103342.appspot.com',
    androidClientId: '3827096841-k0radifoh0r3c7a82vfr8sl7koftuer7.apps.googleusercontent.com',
    iosClientId: '3827096841-inhcd1op8i31198q2p2vq8806frr61gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApW-HSb9rwYf6TcfaaNKhv_9AbbLeJIus',
    appId: '1:3827096841:web:cd0b8467f0961ba71b87d8',
    messagingSenderId: '3827096841',
    projectId: 'my-project-68377-1709184103342',
    authDomain: 'my-project-68377-1709184103342.firebaseapp.com',
    databaseURL: 'https://my-project-68377-1709184103342-default-rtdb.firebaseio.com',
    storageBucket: 'my-project-68377-1709184103342.appspot.com',
    measurementId: 'G-RLTES3D75K',
  );

}